name: auto assign

on:
  pull_request:
    types: [ opened ]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read

    steps:
      - name: set assign
        uses: actions/github-script@v9
        with:
          script: |
            const author = context.payload.pull_request.user.login;
            const pr_number = context.payload.pull_request.number;

            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              assignees: [author],
            });
