name: auto assign

on:
  pull_request_target:
    types: [ opened, reopened ]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: set assign
        uses: actions/github-script@v9
        with:
          script: |
            const author = context.payload.pull_request.user.login;
            const prNumber = context.payload.pull_request.number;

            core.info(`author: ${author}`);
            core.info(`prNumber: ${prNumber}`);

            try {
              await github.rest.issues.checkUserCanBeAssigned({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                assignee: author,
              });

              core.info(`${author} can be assigned`);

              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                assignees: [author],
              });

              core.info(`${author} assigned`);
            } catch (error) {
              core.warning(`status: ${error.status}`);
              core.warning(`message: ${error.message}`);
              core.warning(JSON.stringify(error.response?.data, null, 2));
              throw error;
            }
